"""
pdf_exporter.py — EquiLens AI audit report PDF generator
Drop this file into backend/ alongside main.py
"""

import io
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    HRFlowable, PageBreak
)
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT

# ── Brand colours ────────────────────────────────────────────────────────────
TEAL       = colors.HexColor("#0d9488")
TEAL_LIGHT = colors.HexColor("#ccfbf1")
RED        = colors.HexColor("#ef4444")
AMBER      = colors.HexColor("#f59e0b")
GREEN      = colors.HexColor("#22c55e")
GRAY_DARK  = colors.HexColor("#1e293b")
GRAY_MID   = colors.HexColor("#64748b")
GRAY_LIGHT = colors.HexColor("#f1f5f9")
WHITE      = colors.white


# ── Style helpers ─────────────────────────────────────────────────────────────
def _styles():
    base = getSampleStyleSheet()
    custom = {}

    custom["Title"] = ParagraphStyle(
        "ELTitle", parent=base["Normal"],
        fontSize=24, textColor=WHITE, leading=30,
        fontName="Helvetica-Bold", alignment=TA_LEFT,
    )
    custom["Subtitle"] = ParagraphStyle(
        "ELSubtitle", parent=base["Normal"],
        fontSize=10, textColor=colors.HexColor("#b2f5ea"), leading=14,
        fontName="Helvetica", alignment=TA_LEFT,
    )
    custom["H2"] = ParagraphStyle(
        "ELH2", parent=base["Normal"],
        fontSize=13, textColor=GRAY_DARK, leading=18,
        fontName="Helvetica-Bold", spaceAfter=4,
    )
    custom["Body"] = ParagraphStyle(
        "ELBody", parent=base["Normal"],
        fontSize=9, textColor=GRAY_DARK, leading=14,
        fontName="Helvetica",
    )
    custom["BodyGray"] = ParagraphStyle(
        "ELBodyGray", parent=base["Normal"],
        fontSize=8, textColor=GRAY_MID, leading=12,
        fontName="Helvetica",
    )
    custom["Mono"] = ParagraphStyle(
        "ELMono", parent=base["Normal"],
        fontSize=8, textColor=GRAY_DARK, leading=12,
        fontName="Courier",
    )
    custom["Footer"] = ParagraphStyle(
        "ELFooter", parent=base["Normal"],
        fontSize=7, textColor=GRAY_MID, leading=10,
        fontName="Helvetica", alignment=TA_CENTER,
    )
    return custom


def _severity_color(severity: str):
    s = (severity or "").lower()
    if s == "high":   return RED
    if s == "medium": return AMBER
    return GREEN


def _pill_table(label: str, value: str, color):
    """A small coloured badge rendered as a 1-row Table."""
    t = Table([[Paragraph(f"<b>{label}</b>", ParagraphStyle(
        "pill", fontSize=8, textColor=WHITE, fontName="Helvetica-Bold",
        leading=10, alignment=TA_CENTER,
    )), Paragraph(value, ParagraphStyle(
        "pillv", fontSize=8, textColor=WHITE, fontName="Helvetica",
        leading=10, alignment=TA_CENTER,
    ))]], colWidths=[28*mm, 22*mm])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, 0), color),
        ("BACKGROUND", (1, 0), (1, 0), color),
        ("ROUNDEDCORNERS", [3]),
        ("ALIGN",      (0, 0), (-1, -1), "CENTER"),
        ("VALIGN",     (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING",    (0, 0), (-1, -1), 3),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
    ]))
    return t


# ── Page template (header/footer on every page) ───────────────────────────────
def _on_page(canvas, doc):
    canvas.saveState()
    w, h = A4

    # Top teal stripe
    canvas.setFillColor(TEAL)
    canvas.rect(0, h - 12*mm, w, 12*mm, fill=1, stroke=0)
    canvas.setFillColor(WHITE)
    canvas.setFont("Helvetica-Bold", 8)
    canvas.drawString(15*mm, h - 8*mm, "EquiLens AI  |  Bias Audit Report")
    canvas.setFont("Helvetica", 7)
    canvas.drawRightString(w - 15*mm, h - 8*mm,
                           datetime.now().strftime("%d %b %Y"))

    # Bottom footer line
    canvas.setStrokeColor(GRAY_LIGHT)
    canvas.setLineWidth(0.5)
    canvas.line(15*mm, 12*mm, w - 15*mm, 12*mm)
    canvas.setFillColor(GRAY_MID)
    canvas.setFont("Helvetica", 7)
    canvas.drawCentredString(w / 2, 8*mm,
        f"Page {doc.page}  —  Generated by EquiLens AI · SDG 10 · GDG Solution Challenge 2026")
    canvas.restoreState()


# ── Public API ────────────────────────────────────────────────────────────────
def generate_audit_pdf(report_data: dict) -> bytes:
    """
    Build the audit PDF and return raw bytes.

    Expected keys in report_data:
      dataset, target_col, sensitive_col, audience,
      group_stats   : {group_name: {count, positive_rate}}
      spd, di, eod  : float
      severity      : str  ("High" | "Medium" | "Low")
      bias_detected : bool
      shap_features : [{feature, importance}]   (optional)
      explanation   : str                        (optional, Gemini text)
      intersectionality: {…}                     (optional)
      whatif        : {original, simulated, dropped_features}  (optional)
      remediation_steps: [str]                   (optional)
    """
    buf = io.BytesIO()
    report_data = report_data if isinstance(report_data, dict) else {}

    def _to_float(value, default=0.0):
        try:
            return float(value)
        except (TypeError, ValueError):
            return default

    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=15*mm, rightMargin=15*mm,
        topMargin=20*mm, bottomMargin=20*mm,
    )
    S = _styles()
    story = []

    # ── COVER BLOCK ──────────────────────────────────────────────────────────
    cover_bg = Table(
        [[Paragraph("EquiLens AI", S["Title"])],
         [Paragraph("Algorithmic Bias Audit Report", S["Subtitle"])],
         [Spacer(1, 4*mm)],
         [Paragraph(
             f"Dataset: <b>{report_data.get('dataset', 'N/A')}</b>  &nbsp;|&nbsp;  "
             f"Target: <b>{report_data.get('target_col', 'N/A')}</b>  &nbsp;|&nbsp;  "
             f"Sensitive: <b>{report_data.get('sensitive_col', 'N/A')}</b>",
             ParagraphStyle("covermeta", fontSize=9, textColor=WHITE,
                            fontName="Helvetica", leading=13),
         )],
         [Paragraph(
             datetime.now().strftime("Audit generated %d %B %Y at %H:%M"),
             ParagraphStyle("coverdate", fontSize=8,
                            textColor=colors.HexColor("#b2f5ea"),
                            fontName="Helvetica", leading=12),
         )],
        ],
        colWidths=[doc.width],
    )
    cover_bg.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), TEAL),
        ("TOPPADDING",    (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("LEFTPADDING",   (0, 0), (-1, -1), 8),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 8),
        ("ROUNDEDCORNERS", [4]),
    ]))
    story.append(cover_bg)
    story.append(Spacer(1, 6*mm))

    # ── VERDICT BANNER ───────────────────────────────────────────────────────
    bias_detected = report_data.get("bias_detected", False)
    severity      = report_data.get("severity", "N/A")
    verdict_color = RED if bias_detected else GREEN
    verdict_text  = (
        "BIAS DETECTED — Immediate action recommended."
        if bias_detected else
        "NO SIGNIFICANT BIAS DETECTED — Dataset appears fair."
    )
    verdict_row = Table(
        [[Paragraph(f"<b>{verdict_text}</b>",
                    ParagraphStyle("verdict", fontSize=9, textColor=WHITE,
                                   fontName="Helvetica-Bold", leading=13,
                                   alignment=TA_CENTER))]],
        colWidths=[doc.width],
    )
    verdict_row.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1, -1), verdict_color),
        ("TOPPADDING",    (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("ROUNDEDCORNERS", [3]),
    ]))
    story.append(verdict_row)
    story.append(Spacer(1, 5*mm))

    # ── METRIC SCORECARDS ────────────────────────────────────────────────────
    story.append(Paragraph("Key Fairness Metrics", S["H2"]))
    story.append(HRFlowable(width="100%", thickness=0.5,
                             color=TEAL_LIGHT, spaceAfter=4))

    di  = _to_float(report_data.get("di", 0), 0.0)
    spd = _to_float(report_data.get("spd", 0), 0.0)
    eod = _to_float(report_data.get("eod", 0), 0.0)

    def _metric_cell(name, value, threshold_note, ok):
        bg = GRAY_LIGHT
        val_str = f"{value:.3f}" if value is not None else "N/A"
        status  = "PASS" if ok else "FAIL"
        status_color = GREEN if ok else RED
        inner = Table([
            [Paragraph(f"<b>{name}</b>",
                       ParagraphStyle("mn", fontSize=9, fontName="Helvetica-Bold",
                                      textColor=GRAY_DARK, leading=12))],
            [Paragraph(val_str,
                       ParagraphStyle("mv", fontSize=20, fontName="Helvetica-Bold",
                                      textColor=(GREEN if ok else RED), leading=24))],
            [Paragraph(threshold_note,
                       ParagraphStyle("mt", fontSize=7, fontName="Helvetica",
                                      textColor=GRAY_MID, leading=10))],
            [Paragraph(f"<b>{status}</b>",
                       ParagraphStyle("ms", fontSize=8, fontName="Helvetica-Bold",
                                      textColor=status_color, leading=11))],
        ], colWidths=[55*mm])
        inner.setStyle(TableStyle([
            ("BACKGROUND",    (0, 0), (-1, -1), bg),
            ("ROUNDEDCORNERS", [4]),
            ("TOPPADDING",    (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ("LEFTPADDING",   (0, 0), (-1, -1), 6),
            ("RIGHTPADDING",  (0, 0), (-1, -1), 6),
        ]))
        return inner

    metrics_row = Table(
        [[
            _metric_cell("Disparate Impact", di,
                         "Threshold: >= 0.80  (EEOC 4/5ths rule)",
                         di >= 0.8),
            _metric_cell("Stat. Parity Diff.", spd,
                         "Threshold: <= 0.10",
                         abs(spd) <= 0.1),
            _metric_cell("Equalized Odds", eod,
                         "Threshold: <= 0.10",
                         abs(eod) <= 0.1),
        ]],
        colWidths=[57*mm, 57*mm, 57*mm],
        hAlign="LEFT",
    )
    metrics_row.setStyle(TableStyle([
        ("LEFTPADDING",   (0, 0), (-1, -1), 2),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 2),
        ("VALIGN",        (0, 0), (-1, -1), "TOP"),
    ]))
    story.append(metrics_row)
    story.append(Spacer(1, 5*mm))

    # ── GROUP APPROVAL RATES ─────────────────────────────────────────────────
    group_stats = report_data.get("group_stats", {}) or {}
    if not isinstance(group_stats, dict):
        group_stats = {}

    if group_stats:
        story.append(Paragraph("Group Approval Rates", S["H2"]))
        story.append(HRFlowable(width="100%", thickness=0.5,
                                 color=TEAL_LIGHT, spaceAfter=4))

        tdata = [["Group", "Count", "Approval Rate"]]
        for gname, gvals in group_stats.items():
            gvals = gvals if isinstance(gvals, dict) else {}
            rate = _to_float(gvals.get("positive_rate", 0), 0.0)
            tdata.append([
                str(gname),
                str(gvals.get("count", 0)),
                f"{rate * 100:.1f}%",
            ])

        gtable = Table(tdata, colWidths=[70*mm, 40*mm, 60*mm])
        gtable.setStyle(TableStyle([
            ("BACKGROUND",    (0, 0), (-1, 0),  TEAL),
            ("TEXTCOLOR",     (0, 0), (-1, 0),  WHITE),
            ("FONTNAME",      (0, 0), (-1, 0),  "Helvetica-Bold"),
            ("FONTSIZE",      (0, 0), (-1, -1), 9),
            ("ROWBACKGROUNDS",(0, 1), (-1, -1), [WHITE, GRAY_LIGHT]),
            ("GRID",          (0, 0), (-1, -1), 0.3, colors.HexColor("#e2e8f0")),
            ("TOPPADDING",    (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ("LEFTPADDING",   (0, 0), (-1, -1), 6),
            ("ALIGN",         (1, 0), (-1, -1), "CENTER"),
        ]))
        story.append(gtable)
        story.append(Spacer(1, 5*mm))

    # ── SHAP FEATURE IMPORTANCE ───────────────────────────────────────────────
    shap = report_data.get("shap_features", []) or []
    if not isinstance(shap, list):
        shap = []

    if shap:
        story.append(Paragraph("Top Contributing Features (SHAP)", S["H2"]))
        story.append(HRFlowable(width="100%", thickness=0.5,
                                 color=TEAL_LIGHT, spaceAfter=4))

        sdata = [["Feature", "Importance", "Bar"]]
        max_imp = max(
            (
                _to_float(f.get("importance", 0), 0.0)
                for f in shap
                if isinstance(f, dict)
            ),
            default=1,
        ) or 1
        for feat in shap[:10]:
            if not isinstance(feat, dict):
                continue

            imp  = _to_float(feat.get("importance", 0), 0.0)
            bar_w = int((imp / max_imp) * 40)
            sdata.append([
                str(feat.get("feature", "N/A")),
                f"{imp:.4f}",
                Paragraph(
                    "&#9608;" * bar_w,
                    ParagraphStyle("bar", fontSize=6, textColor=TEAL,
                                   fontName="Helvetica", leading=8),
                ),
            ])

        stable = Table(sdata, colWidths=[70*mm, 30*mm, 70*mm])
        stable.setStyle(TableStyle([
            ("BACKGROUND",    (0, 0), (-1, 0),  TEAL),
            ("TEXTCOLOR",     (0, 0), (-1, 0),  WHITE),
            ("FONTNAME",      (0, 0), (-1, 0),  "Helvetica-Bold"),
            ("FONTSIZE",      (0, 0), (-1, -1), 8),
            ("ROWBACKGROUNDS",(0, 1), (-1, -1), [WHITE, GRAY_LIGHT]),
            ("GRID",          (0, 0), (-1, -1), 0.3, colors.HexColor("#e2e8f0")),
            ("TOPPADDING",    (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ("LEFTPADDING",   (0, 0), (-1, -1), 6),
            ("ALIGN",         (1, 0), (1, -1),  "CENTER"),
        ]))
        story.append(stable)
        story.append(Spacer(1, 5*mm))

    # ── AI EXPLANATION ────────────────────────────────────────────────────────
    explanation = report_data.get("explanation", "N/A")
    if explanation and explanation != "N/A":
        story.append(Paragraph("AI Explanation (Gemini)", S["H2"]))
        story.append(HRFlowable(width="100%", thickness=0.5,
                                 color=TEAL_LIGHT, spaceAfter=4))
        # Strip the fallback asterisk if present
        clean_exp = explanation.lstrip("* ").strip()
        exp_box = Table(
            [[Paragraph(clean_exp, S["Body"])]],
            colWidths=[doc.width],
        )
        exp_box.setStyle(TableStyle([
            ("BACKGROUND",    (0, 0), (-1, -1), GRAY_LIGHT),
            ("ROUNDEDCORNERS", [4]),
            ("TOPPADDING",    (0, 0), (-1, -1), 8),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
            ("LEFTPADDING",   (0, 0), (-1, -1), 10),
            ("RIGHTPADDING",  (0, 0), (-1, -1), 10),
        ]))
        story.append(exp_box)
        story.append(Spacer(1, 5*mm))

    # ── WHAT-IF RESULTS (if present) ─────────────────────────────────────────
    whatif = report_data.get("whatif", {}) or {}
    if not isinstance(whatif, dict):
        whatif = {}

    if whatif:
        story.append(PageBreak())
        story.append(Paragraph("What-If Simulation Results", S["H2"]))
        story.append(HRFlowable(width="100%", thickness=0.5,
                                 color=TEAL_LIGHT, spaceAfter=4))

        dropped = whatif.get("dropped_features", []) or []
        if not isinstance(dropped, list):
            dropped = []

        story.append(Paragraph(
            f"Features dropped: <b>{', '.join(dropped) if dropped else 'None'}</b>",
            S["Body"],
        ))
        story.append(Spacer(1, 3*mm))

        orig = whatif.get("original", {}) or {}
        sim  = whatif.get("simulated", {}) or {}
        if not isinstance(orig, dict):
            orig = {}
        if not isinstance(sim, dict):
            sim = {}

        wi_data = [["Metric", "Before", "After", "Change"]]
        for metric, label, fmt in [
            ("di",  "Disparate Impact",   lambda v: f"{v:.3f}"),
            ("spd", "Stat. Parity Diff.", lambda v: f"{v*100:.1f}%"),
            ("eod", "Equalized Odds",     lambda v: f"{v*100:.1f}%"),
        ]:
            ov = orig.get(metric)
            sv = sim.get(metric)
            if ov is not None and sv is not None:
                ov = _to_float(ov, 0.0)
                sv = _to_float(sv, 0.0)
                delta = sv - ov
                sign  = "+" if delta > 0 else ""
                wi_data.append([label, fmt(ov), fmt(sv),
                                 f"{sign}{fmt(delta)}"])

        wi_table = Table(wi_data, colWidths=[60*mm, 35*mm, 35*mm, 40*mm])
        wi_table.setStyle(TableStyle([
            ("BACKGROUND",    (0, 0), (-1, 0),  TEAL),
            ("TEXTCOLOR",     (0, 0), (-1, 0),  WHITE),
            ("FONTNAME",      (0, 0), (-1, 0),  "Helvetica-Bold"),
            ("FONTSIZE",      (0, 0), (-1, -1), 9),
            ("ROWBACKGROUNDS",(0, 1), (-1, -1), [WHITE, GRAY_LIGHT]),
            ("GRID",          (0, 0), (-1, -1), 0.3, colors.HexColor("#e2e8f0")),
            ("TOPPADDING",    (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ("LEFTPADDING",   (0, 0), (-1, -1), 6),
            ("ALIGN",         (1, 0), (-1, -1), "CENTER"),
        ]))
        story.append(wi_table)
        story.append(Spacer(1, 5*mm))

    # ── REMEDIATION STEPS ─────────────────────────────────────────────────────
    steps = report_data.get("remediation_steps", []) or []
    if not isinstance(steps, list):
        steps = []

    if steps:
        story.append(Paragraph("Recommended Remediation Steps", S["H2"]))
        story.append(HRFlowable(width="100%", thickness=0.5,
                                 color=TEAL_LIGHT, spaceAfter=4))
        for i, step in enumerate(steps, 1):
            story.append(Paragraph(
                f"{i}.&nbsp;&nbsp;{str(step)}",
                ParagraphStyle("step", parent=S["Body"],
                               leftIndent=8, spaceAfter=4),
            ))
        story.append(Spacer(1, 5*mm))

    # ── REGULATION COMPLIANCE ────────────────────────────────────────────────
    story.append(Paragraph("Regulation Compliance Reference", S["H2"]))
    story.append(HRFlowable(width="100%", thickness=0.5,
                             color=TEAL_LIGHT, spaceAfter=4))
    reg_data = [
        ["Regulation", "Metric", "Threshold", "Status"],
        ["EEOC 4/5ths Rule", "Disparate Impact", ">= 0.80",
            "PASS" if di >= 0.8 else "FAIL"],
        ["EU AI Act", "Stat. Parity Diff.", "<= 0.10",
            "PASS" if abs(spd) <= 0.1 else "FAIL"],
        ["General Fairness", "Equalized Odds", "<= 0.10",
            "PASS" if abs(eod) <= 0.1 else "FAIL"],
    ]
    reg_table = Table(reg_data, colWidths=[60*mm, 45*mm, 35*mm, 30*mm])
    reg_table.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1, 0),  TEAL),
        ("TEXTCOLOR",     (0, 0), (-1, 0),  WHITE),
        ("FONTNAME",      (0, 0), (-1, 0),  "Helvetica-Bold"),
        ("FONTSIZE",      (0, 0), (-1, -1), 9),
        ("ROWBACKGROUNDS",(0, 1), (-1, -1), [WHITE, GRAY_LIGHT]),
        ("GRID",          (0, 0), (-1, -1), 0.3, colors.HexColor("#e2e8f0")),
        ("TOPPADDING",    (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING",   (0, 0), (-1, -1), 6),
        ("ALIGN",         (3, 1), (3, -1),  "CENTER"),
    ]))
    # Colour PASS/FAIL cells
    for row_i, row in enumerate(reg_data[1:], start=1):
        cell_color = GREEN if row[3] == "PASS" else RED
        reg_table.setStyle(TableStyle([
            ("TEXTCOLOR", (3, row_i), (3, row_i), cell_color),
            ("FONTNAME",  (3, row_i), (3, row_i), "Helvetica-Bold"),
        ]))
    story.append(reg_table)
    story.append(Spacer(1, 8*mm))

    # ── DISCLAIMER ────────────────────────────────────────────────────────────
    story.append(HRFlowable(width="100%", thickness=0.5, color=GRAY_LIGHT))
    story.append(Spacer(1, 3*mm))
    story.append(Paragraph(
        "This report was generated automatically by EquiLens AI. "
        "Metrics are computed using SPD, Disparate Impact (EEOC 4/5ths rule), "
        "and Equalized Odds. SHAP values indicate feature contribution to model "
        "predictions. This report does not constitute legal advice. "
        "EquiLens AI · SDG 10 · GDG Solution Challenge 2026",
        S["BodyGray"],
    ))

    doc.build(story, onFirstPage=_on_page, onLaterPages=_on_page)
    return buf.getvalue()